#pragma once

#include "./controls/control.h"

#include "./controls/bitmap.h"
#include "./controls/blinking-button.h"
#include "./controls/button.h"
#include "./controls/check-box.h"
#include "./controls/combo-box.h"
#include "./controls/dual-button.h"
#include "./controls/edit-box.h"
#include "./controls/file-combo-box.h"
#include "./controls/file-list-box.h"
#include "./controls/graph.h"
#include "./controls/line-graph.h"
#include "./controls/list-box.h"
#include "./controls/list-box-string.h"
#include "./controls/movie.h"
#include "./controls/radio-button.h"
#include "./controls/scalable-button.h"
#include "./controls/scroll-bar.h"
#include "./controls/scroll-button.h"
#include "./controls/slider.h"
#include "./controls/status-bar.h"
#include "./controls/text-label.h"
#include "./controls/text-label-scrolling.h"
#include "./controls/tristate-check-box.h"
