#pragma once


#define MODDING_NAMESPACE ee::modding

#define MODDING_NAMESPACE_BEGIN namespace MODDING_NAMESPACE {
#define MODDING_NAMESPACE_END }


#define MODDING_CORE_NAMESPACE MODDING_NAMESPACE::core

#define MODDING_CORE_NAMESPACE_BEGIN namespace MODDING_CORE_NAMESPACE {
#define MODDING_CORE_NAMESPACE_END }
